-- Step 3.3: Create Leads table (same schema as SQL)
-- Run after 02_create_database.sql

USE DATABASE LEADMANAGEMENT;
USE WAREHOUSE LEAD_WH;
USE SCHEMA PUBLIC;

CREATE TABLE IF NOT EXISTS LEADS (
    ROWID INTEGER,
    ID VARCHAR(36) NOT NULL,
    STATE INTEGER NOT NULL,
    CREATEDDATEUTC TIMESTAMP_NTZ,
    CANCELLATIONREQUESTDATEUTC TIMESTAMP_NTZ,
    CANCELLATIONDATEUTC TIMESTAMP_NTZ,
    CANCELLATIONREJECTIONDATEUTC TIMESTAMP_NTZ,
    SOLDEMPLOYEE VARCHAR(255),
    CANCELLEDEMPLOYEE VARCHAR(255),
    UPDATEDDATEUTC TIMESTAMP_NTZ
);
