-- Step 4: Create LeadEvents table for Python transformation output
-- Run after 03_create_leads_table.sql (and after LEADS has data from ADF)

USE DATABASE LEADMANAGEMENT;
USE WAREHOUSE LEAD_WH;
USE SCHEMA PUBLIC;

CREATE TABLE IF NOT EXISTS LEADEVENTS (
    ID VARCHAR(36) NOT NULL,
    EVENTTYPE VARCHAR(50) NOT NULL,
    EVENTEMPLOYEE VARCHAR(255),
    EVENTDATE TIMESTAMP_NTZ,
    LEADID VARCHAR(36) NOT NULL,
    UPDATEDDATEUTC TIMESTAMP_NTZ
);
